### ISSUE TITLE
Need some help

### ISSUE THREAD

**Issue by webguy210** [Zaid-Safadi/dicom-webJS#7]
I found your open source project here on github.  I am working with a client that wants a DICOM server and 10+ viewer clients.  I have looked at your online demo page and it is close to meeting their requirements.  I need a few missing features:

   1 - show preview of the DICOM images in the search results on your "Query & Retrieve" page
   2 - ability to show 2 images side by side in the "Viewer" page
   3 - ability to show 4 images (2x2) in the "Viewer" page

Can I contact you privately to discuss this?

**Comment by Zaid-Safadi** [comment]
You can contact me at zsafadi11@gmail.com

**Comment by Zaid-Safadi** [comment]
#2 and #3 can be acheived in the Cornerstone viewer and #1 can be supported using the WADO-URL endpoint.
Feel free to open this if you need any further help
